// Fetching user session
const GET_SESSION_FETCH = "GET_SESSION_FETCH";

// Get user session success
const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";

// Fetching user sign up
const GET_SIGNUP_FETCH = "GET_SIGNUP_FETCH";

// Sign up
const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";

// Fetching user sign in
const GET_SIGNIN_FETCH = "GET_SIGNIN_FETCH";

// Sign in
const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";

// Fetching user sign out
const GET_SIGNOUT_FETCH = "GET_SIGNOUT_FETCH";

// Sign out
const GET_SIGNOUT_SUCCESS = "GET_SIGNOUT_SUCCESS";

// Save favorited book fetch
const GET_SAVE_FAVORITED_BOOK_FETCH = "GET_SAVE_FAVORITED_BOOK_FETCH";

// Save favorited book success
const GET_SAVE_FAVORITED_BOOK_SUCCESS = "GET_SAVE_FAVORITED_BOOK_SUCCESS";

// Remove favorited book fetch
const GET_REMOVE_FAVORITED_BOOK_FETCH = "GET_REMOVE_FAVORITED_BOOK_FETCH";

// Remove favorited book success
const GET_REMOVE_FAVORITED_BOOK_SUCCESS = "GET_REMOVE_FAVORITED_BOOK_SUCCESS";

export const userTypes = {
  GET_SESSION_FETCH,
  GET_SESSION_SUCCESS,
  GET_SIGNUP_FETCH,
  GET_SIGNUP_SUCCESS,
  GET_SIGNIN_FETCH,
  GET_SIGNIN_SUCCESS,
  GET_SIGNOUT_FETCH,
  GET_SIGNOUT_SUCCESS,
  GET_SAVE_FAVORITED_BOOK_SUCCESS,
  GET_SAVE_FAVORITED_BOOK_FETCH,
  GET_REMOVE_FAVORITED_BOOK_FETCH,
  GET_REMOVE_FAVORITED_BOOK_SUCCESS
};
