// Get user session
const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";

// Sign up
const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";

// Sign in
const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";

// Sign out
const GET_SIGNOUT_SUCCESS = "GET_SIGNOUT_SUCCESS";

// Save favorited book fetch
const GET_SAVE_FAVORITED_BOOK_FETCH = "GET_SAVE_FAVORITED_BOOK_FETCH";

// Save favorited book success
const GET_SAVE_FAVORITED_BOOK_SUCCESS = "GET_SAVE_FAVORITED_BOOK_SUCCESS";

export const userTypes = {
  GET_SESSION_SUCCESS,
  GET_SIGNUP_SUCCESS,
  GET_SIGNIN_SUCCESS,
  GET_SIGNOUT_SUCCESS,
  GET_SAVE_FAVORITED_BOOK_SUCCESS,
  GET_SAVE_FAVORITED_BOOK_FETCH,
};
